/*
 * DIO_private.h
 *
 *  Created on: Mar 12, 2017
 *      Author: Ahmed HAmdy
 */

#ifndef DIO_PRIVATE_H_
#define DIO_PRIVATE_H_


/* Comment: Concatenation */
#define CONC_HELPER(x7,x6,x5,x4,x3,x2,x1,x0)	0b##x7##x6##x5##x4##x3##x2##x1##x0
#define CONC(x7,x6,x5,x4,x3,x2,x1,x0)			CONC_HELPER(x7,x6,x5,x4,x3,x2,x1,x0)

/* Comment: Set Initial Direction for Ports */
#define DIO_u8PORTA_DIRECTION	CONC(DIO_u8PIN7_INTIAL_DIRECTION,DIO_u8PIN6_INTIAL_DIRECTION,DIO_u8PIN5_INTIAL_DIRECTION,DIO_u8PIN4_INTIAL_DIRECTION,DIO_u8PIN3_INTIAL_DIRECTION,DIO_u8PIN2_INTIAL_DIRECTION,DIO_u8PIN1_INTIAL_DIRECTION,DIO_u8PIN0_INTIAL_DIRECTION)
#define DIO_u8PORTB_DIRECTION	CONC(DIO_u8PIN15_INTIAL_DIRECTION,DIO_u8PIN14_INTIAL_DIRECTION,DIO_u8PIN13_INTIAL_DIRECTION,DIO_u8PIN12_INTIAL_DIRECTION,DIO_u8PIN11_INTIAL_DIRECTION,DIO_u8PIN10_INTIAL_DIRECTION,DIO_u8PIN9_INTIAL_DIRECTION,DIO_u8PIN8_INTIAL_DIRECTION)
#define DIO_u8PORTC_DIRECTION	CONC(DIO_u8PIN23_INTIAL_DIRECTION,DIO_u8PIN22_INTIAL_DIRECTION,DIO_u8PIN21_INTIAL_DIRECTION,DIO_u8PIN20_INTIAL_DIRECTION,DIO_u8PIN19_INTIAL_DIRECTION,DIO_u8PIN18_INTIAL_DIRECTION,DIO_u8PIN17_INTIAL_DIRECTION,DIO_u8PIN16_INTIAL_DIRECTION)
#define DIO_u8PORTD_DIRECTION	CONC(DIO_u8PIN31_INTIAL_DIRECTION,DIO_u8PIN30_INTIAL_DIRECTION,DIO_u8PIN29_INTIAL_DIRECTION,DIO_u8PIN28_INTIAL_DIRECTION,DIO_u8PIN27_INTIAL_DIRECTION,DIO_u8PIN26_INTIAL_DIRECTION,DIO_u8PIN25_INTIAL_DIRECTION,DIO_u8PIN24_INTIAL_DIRECTION)

/* Comment: Set Initial Value for Ports */
#define DIO_u8PORTA_VALUE	CONC(DIO_u8PIN7_INTIAL_VALUE,DIO_u8PIN6_INTIAL_VALUE,DIO_u8PIN5_INTIAL_VALUE,DIO_u8PIN4_INTIAL_VALUE,DIO_u8PIN3_INTIAL_VALUE,DIO_u8PIN2_INTIAL_VALUE,DIO_u8PIN1_INTIAL_VALUE,DIO_u8PIN0_INTIAL_VALUE)
#define DIO_u8PORTB_VALUE	CONC(DIO_u8PIN15_INTIAL_VALUE,DIO_u8PIN14_INTIAL_VALUE,DIO_u8PIN13_INTIAL_VALUE,DIO_u8PIN12_INTIAL_VALUE,DIO_u8PIN11_INTIAL_VALUE,DIO_u8PIN10_INTIAL_VALUE,DIO_u8PIN9_INTIAL_VALUE,DIO_u8PIN8_INTIAL_VALUE)
#define DIO_u8PORTC_VALUE	CONC(DIO_u8PIN23_INTIAL_VALUE,DIO_u8PIN22_INTIAL_VALUE,DIO_u8PIN21_INTIAL_VALUE,DIO_u8PIN20_INTIAL_VALUE,DIO_u8PIN19_INTIAL_VALUE,DIO_u8PIN18_INTIAL_VALUE,DIO_u8PIN17_INTIAL_VALUE,DIO_u8PIN16_INTIAL_VALUE)
#define DIO_u8PORTD_VALUE	CONC(DIO_u8PIN31_INTIAL_VALUE,DIO_u8PIN30_INTIAL_VALUE,DIO_u8PIN29_INTIAL_VALUE,DIO_u8PIN28_INTIAL_VALUE,DIO_u8PIN27_INTIAL_VALUE,DIO_u8PIN26_INTIAL_VALUE,DIO_u8PIN25_INTIAL_VALUE,DIO_u8PIN24_INTIAL_VALUE)

/* PORT A Registers */
#define DDR_A 	    (*(volatile u8 *) (0x3A) )
#define PORT_A 	    (*(volatile u8 *) (0x3B) )
#define PIN_A	    (*(volatile u8 *) (0x39) )

/* PORT B Registers */
#define DDR_B		(*(volatile u8 *) (0x37) )
#define PORT_B      (*(volatile u8 *) (0x38) )
#define PIN_B		(*(volatile u8 *) (0x36) )

/* PORT C Registers */
#define DDR_C	    (*(volatile u8 *) (0x34) )
#define PORT_C	    (*(volatile u8 *) (0x35) )
#define PIN_C	    (*(volatile u8 *) (0x33) )

/* PORT D Registers */
#define DDR_D	    (*(volatile u8 *) (0x31) )
#define PORT_D	    (*(volatile u8 *) (0x32) )
#define PIN_D	    (*(volatile u8 *) (0x30) )
#endif /* DIO_PRIVATE_H_ */
